function TelepulesValaszto(){
    var Valasztott=document.getElementById("telepulesek").value;
    var SzovegSection = document.querySelector(".TelepulesSection");
    var TerkepDiv = document.querySelector(".MapDiv");
    var Carousel = document.querySelector(".TelepulesekCarouselInner");

    if(Valasztott=="default"){
        SzovegSection.innerHTML="";
        TerkepDiv.innerHTML="<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d438263.1577196499!2d18.075539940982026!3d47.57784560642539!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x476a2d2a97480765%3A0x1a85616c19913726!2sKom%C3%A1rom-Esztergom!5e1!3m2!1shu!2shu!4v1710791065915!5m2!1shu!2shu\" width=\"600\" height=\"450\" style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>";
        
    }else if(Valasztott=="neszmely"){
        SzovegSection.innerHTML="<h3>Neszmély</h3><p>Neszmély Magyarország határán, a Duna mellett helyzkedik el.<br>Mi 5 darab látványosságot néztünk itt meg, igaz, vannak egyéb látogatásra érdemes helyek.<br>Ezek a helyek a következőek:</p><ul><li>Skanzen</li><li>Kemencék</li><li>Komp</li><li>Vasút</li><li>Apáca zárda/laktanya</li></ul>";
        TerkepDiv.innerHTML="<iframe src=\"https://www.google.com/maps/d/u/1/embed?mid=1EyD9ICgsGKkvPnzuZAUEQYa-34BXQKY&ehbc=2E312F\" width=\"100%\" height=\"480\"></iframe>";
        Carousel.innerHTML=`<div class="carousel-item"><img class="img-fluid" src="../media/images/n1.jpg" alt=""></div><div class="carousel-item"><img class="img-fluid" src="../media/images/n2.jpg" alt=""></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/n1.mp4" type="video/mp4"></video></div><div class="carousel-item active"><video class="img-fluid" controls><source src="../media/videos/n2.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/n3.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/n4.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/n5.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/n6.mp4" type="video/mp4"></video></div>`;
    }else if(Valasztott=="dunaalmas"){
        SzovegSection.innerHTML="<h3>Dunaalmás</h3><p>Dunaalmás Magyarország északi határán található. <br> E telepűlés volt túránk második álomása. Itt lakik Bélai Dominik Péter munkatárs.<br> E telepűlésen 9 látványosságot tekintettünk meg:</p><ul><li>Lilla forrás</li><li>Művház & Lilla szoba</li><li>Csokonai mellszobor</li><li>Lilla sírja</li><li>Körmedence</li><li>Pihenőtó</li><li>Malom</li><li>Csata emlékmű</li><li>Által-ér torkolat</li></ul>";
        TerkepDiv.innerHTML="<iframe src=\"https://www.google.com/maps/d/u/1/embed?mid=19ccXMTKl92IcA6fxT3BQRK1Ci188EnY&ehbc=2E312F\" width=\"100%\" height=\"480\"></iframe>";
        Carousel.innerHTML =`<div class="carousel-item"><img src="../media/images/a1.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a2.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a3.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a4.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a5.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a6.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a7.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a8.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a9.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a10.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a11.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a12.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a13.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/a14.jpg" alt=""></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d1.mp4" type="video/mp4"></video></div><div class="carousel-item active"><video class="img-fluid" controls><source src="../media/videos/d2.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d3.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d4.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d5.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d6.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d7.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/d8.mp4" type="video/mp4"></video></div>`;

    }else if(Valasztott=="tata"){
        SzovegSection.innerHTML="<h3>Tata</h3><p>Tata szintén Magyarország északi részén található. <br> E telepűlés volt túránk harmadik álomása. <br> Ezen a telepűlésen 11 látványosságot tekintettünk meg:</p><ul><li>Fényes</li><li>Laktanya</li><li>Vár</li><li>Öreg-tó</li><li>Angolpark</li><li>Műromok</li><li>Szabadtéri színpad</li><li>Cseke-tó</li><li>Kajakház</li><li>Régi KISZ tábor</li><li>Cocoon</li></ul>";
        TerkepDiv.innerHTML="<iframe src=\"https://www.google.com/maps/d/u/1/embed?mid=1eJ2SEi7apcj0jE_Cne-F_A-8CPR8aBw&ehbc=2E312F\" width=\"100%\" height=\"480\"></iframe>";
        Carousel.innerHTML=`<div class="carousel-item"><img src="../media/images/t1.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t2.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t3.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t4.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t5.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t6.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t7.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t8.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t9.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t10.jpg" alt=""></div><div class="carousel-item"><img src="../media/images/t11.jpg" alt=""></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta1.mp4" type="video/mp4"></video></div><div class="carousel-item active"><video class="img-fluid" controls><source src="../media/videos/ta2.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta3.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta4.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta5.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta6.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta7.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta8.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta9.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta10.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta11.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/ta12.mp4" type="video/mp4"></video></div><div class="carousel-item"><video class="img-fluid" controls>
        <source src="../media/videos/ta13.mp4" type="video/mp4"></video></div>`;
    }else if(Valasztott=="vertesszolos"){
        SzovegSection.innerHTML="<h3>Vértesszőlős</h3><p>Vértesszőlős egy kis telepűlés észak Magyarországon.<br> Ez a telepűlés volt túránk negyedik álomása.<br> A telepűlés 4 látványosságáról beszéltünk meg:</p><ul><li>Kiskacsás tó</li><li>Levendulás</li><li>Régészeti múzeum</li><li>Szedd magad eper</li></ul>";
        TerkepDiv.innerHTML="<iframe src=\"https://www.google.com/maps/d/u/1/embed?mid=1SkS5_ul0ClLaflD1Q3IGuUjfn8KW5HU&ehbc=2E312F\" width=\"100%\" height=\"480\"></iframe>";
        Carousel.innerHTML=`<div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/sz1.mp4" type="video/mp4"></video></div><div class="carousel-item active"><video class="img-fluid" controls><source src="../media/videos/sz2.mp4" type="video/mp4"></video></div>`;
    }else{
        SzovegSection.innerHTML="<h3>Tatabánya</h3><p>Tatabánya Komárom Eszterom Vármegye megyeszékhelye A kockázati tényzők miatt a túránk utolsó telepűlése. <br> E telepűlésen 10 látványosságot tekintettünk meg:</p><ul><li>Rákóczi tér</li><li>Galla-patak</li><li>Fő tér</li><li>Agóra</li><li>Jubileum park</li><li>Csónakázó tó</li><li>Máltai játszótér</li><li>Puskin</li><li>Bánhidai templom</li><li>Erőmű tó</li></ul>"
        TerkepDiv.innerHTML="<iframe src=\"https://www.google.com/maps/d/u/1/embed?mid=1-5lBYTS8chnznuEYJfUNqYJkS8OQuT4&ehbc=2E312F\" width=\"100%\" height=\"480\"></iframe>"
        Carousel.innerHTML=`<div class="carousel-item"><video class="img-fluid" controls><source src="../media/videos/tb1.mp4" type="video/mp4"></video></div><div class="carousel-item active"><video class="img-fluid" controls><source src="../media/videos/tbvege.mp4" type="video/mp4"></video></div>`;
    }
}
